name: Code quality

on:
  - push
  - pull_request

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Setup pnpm
       uses: pnpm/action-setup@v4
       with:
          version: 8

     - name: Install dependencies
       run: pnpm i

     - name: Setup Biome
       uses: biomejs/setup-biome@v2
       with:
          version: latest

     - name: Run Check
       run: pnpm check && pnpm ci
